### ISSUE TITLE
set to another language (After rebooting, it changes to English.)

### ISSUE THREAD

**Issue by Jshuns** [bigtreetech/CB1#124]
I am using version 2.3.2.

I changed it to use my language, and when I reboot it comes back to English.

can't be solved.

**Comment by bigtreetech** [comment]
This issue is a bug in the KlipperScreen https://github.com/KlipperScreen/KlipperScreen/issues/1015 for a period of time. The default installed version in the CB1 OS does not have this issue, and the latest version of KlipperScreen has also resolved this issue. 

Anyway, updating KlipperScreen to the latest version can solve this problem
