### ISSUE TITLE
cb1 Emma won't work with the hermit crab CAN

### ISSUE THREAD

**Issue by lotfinoluffy** [bigtreetech/CB1#142]
hi everyone 

trying to install hermit crab can version into a manta board, everything is installed but im trying to use the Biqu raspberry pi can hat in the hermit crab kit, but it just doesn't work, and if certain settings are activated in the boardenv.txt it won't even boot (like the ws2812

also anyone knows what's the difference between the spidev int eh boardenv file ?? 0_0 1_0 1_1 and 1_2 ? is it related to cb1 version or something ??

does the hermit crab CAN hat works with the CB1, according to the pinout of both it should I think but was thinking is the reason its not working, but might be mistaken

not sure how or if its possible to use both the board can chip and the hermit crab can together, since there's no easy way to connect them both in can

**Comment by Pneumanifest** [comment]
The raspberry pi can hat is made to be used with raspberry pi not the cb1. You install a raspberry pi CM4 on the Manta m4p then you will be able to use it. Otherwise you will need to get the IO2Can adapter that is made to be used with the CB1. The CB1 is very similar but is not a 1 to 1 clone of the raspberry pi, it's an alternative solution.
