### ISSUE TITLE
V2.2.0 - CB1_Debian11_bullseye_Klipper_kernel5.16_20220929.img.xz (32GB Card Needed)

### ISSUE THREAD

**Issue by o1hitman1o** [bigtreetech/CB1#46]
It should be noted that you need to use a 32GB SD card if you are going to be flashing the V2.2.0 CB1_Debian11_bullseye_Klipper_kernel5.16_20220929.img.xz image that was uploaded.
I was using a 16GB card and it keep failing.

**Comment by thisiskeithb** [comment]
Something was probably wrong with your 16GB SD card since `CB1_Debian11_bullseye_Klipper_kernel5.16_20220929.img.xz` works fine on an 8GB SD card. There's even room to spare:

<img width="659" alt="image" src="https://user-images.githubusercontent.com/13375512/194449170-9980bc43-b6a3-441c-8bc5-3536a17bd1f5.png">

I'd recommend using the official [SD Memory Card Formatter tool](https://www.sdcard.org/downloads/formatter/) and reformatting the 16GB card.

**Comment by o1hitman1o** [comment]
Hmmm... Not sure.  I did try multiple SD cards but it only completed flash on the 32 GB card.

**Comment by looxonline** [comment]
16GB card works just fine.

**Comment by o1hitman1o** [comment]
Must work then.
